apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cachestatic-backend
  labels:
    app: cachestatic-backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cachestatic-backend
    spec:
      containers:
      - name: cachestatic-backend
        image: acoshift/cachestatic-backend:1.0.0
        livenessProbe:
          httpGet:
            path: /
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cachestatic-backend
  labels:
    app: cachestatic-backend
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: cachestatic-backend
